const perfis = [
  {
    id: 1,
    imagem: "assets/images/alien-01.jpg",
    nome: "K'rrak Chitin",
    idade_relativa: "60–79%",
    especie: "Ecteídios",
    genero: "Outro",
    pronomes: "Ele / dele",
    planeta: "Zhynx - WX",
    linguagem_amor: "Briga e desafetos",
    hobby: "Exploração espacial",
    deuses: "2–5",
    filhos: "11+",
    monogamia: "Sim",
    teletransporte_etico: "Não",
    compatibilidade: "Média",
    eles_usaram: "Raramente",
    eu_usei: "Frequentemente"
  },
  {
    id: 2,
    imagem: "assets/images/alien-02.jpg",
    nome: "Nymphaea Vael",
    idade_relativa: "20–29%",
    especie: "Glorbs",
    genero: "Feminino",
    pronomes: "Ela / dela",
    planeta: "Polyestar - RE",
    linguagem_amor: "Tempo de qualidade",
    hobby: "Arte",
    deuses: "100+",
    filhos: "Nenhum",
    monogamia: "Não",
    teletransporte_etico: "Sim",
    compatibilidade: "Alta",
    eles_usaram: "Nunca",
    eu_usei: "Nunca"
  },
  {
    id: 3,
    imagem: "assets/images/alien-03.jpg",
    nome: "Unit-7X",
    idade_relativa: "30–44%",
    especie: "Sintéticos",
    genero: "Sem gênero",
    pronomes: "Não sei / não se aplica",
    planeta: "Zaun - AR",
    linguagem_amor: "Serviço",
    hobby: "Ciência",
    deuses: "0",
    filhos: "Nenhum",
    monogamia: "Sim",
    teletransporte_etico: "Sim",
    compatibilidade: "Nenhuma",
    eles_usaram: "Frequentemente",
    eu_usei: "Nunca"
  },
  {
    id: 4,
    imagem: "assets/images/alien-04.jpg",
    nome: "Szzorath",
    idade_relativa: "45–59%",
    especie: "Reptilianos",
    genero: "Masculino",
    pronomes: "Ele / dele",
    planeta: "Bogus - BI",
    linguagem_amor: "Presentes",
    hobby: "Jogos",
    deuses: "1",
    filhos: "4–10",
    monogamia: "Não",
    teletransporte_etico: "Não",
    compatibilidade: "Alta",
    eles_usaram: "Nunca",
    eu_usei: "Raramente"
  },
  {
    id: 5,
    imagem: "assets/images/alien-05.jpg",
    nome: "Aethelgard 9",
    idade_relativa: "30–44%",
    especie: "Híbridos",
    genero: "Não-binário",
    pronomes: "Elu / delu",
    planeta: "Terra - VL",
    linguagem_amor: "Palavras de afirmação",
    hobby: "Música",
    deuses: "11–100",
    filhos: "1",
    monogamia: "Sim",
    teletransporte_etico: "Sim",
    compatibilidade: "Média",
    eles_usaram: "Nunca",
    eu_usei: "Nunca"
  }
];

// Imagem usada de fundo borrado para o card que está "bloqueado" aguardando o timer
const perfilBloqueadoDeFundo = {
  imagem: "assets/images/alien-02.jpg",
  nome: "Próximo ser misterioso...",
  especie: "Sinal criptografado"
};